#!/usr/bin/env bash

#Total device count setting to zero initially
total_dev=0

## DEVICE ID & MODEL EXTARCT ##
dev=$(bash modules/HelperFunctions/GetDevices)

if [ "$dev" != "" ];
then
    total_dev=${#dev[@]}
fi


# Setting the properties variable
properties=""

function get_prop_details () {
    
    prop=$(echo "$properties" | grep "$1" | awk '{$1= ""; print $0}' | xargs | sed 's/\[//' | sed 's/\]//')
    echo "$prop"
    
}

function print_info () {
    
    modelname=$1

    echo -e "\n\e[1;93mThe Details of the device \e[1;92m$modelname \e[93mare :- "
    echo -e "\n\e[1;92mModel \e[1;94m= \e[1;93m$model"
    echo -e "\e[1;92mDevice \e[1;94m= \e[1;93m$device"
    echo -e "\e[1;92mBrand \e[1;94m= \e[1;93m$brand"
    echo -e "\e[1;92mBuild Date \e[1;94m= \e[1;93m$build_date"
    echo -e "\e[1;92mAndroid \e[1;94m= \e[1;93m$android"
    echo -e "\e[1;92mSDK Version \e[1;94m= \e[1;93m$sdk_version"
    echo -e "\e[1;92mSim Card \e[1;94m= \e[1;93m$sim"
    echo -e "\e[1;92mChipset \e[1;94m= \e[1;93m$chipset"
    echo -e "\e[1;92mSecurity Patch  \e[1;94m= \e[1;93m$security_patch"
    echo -e "\e[1;92mEncryption State \e[1;94m= \e[1;93m$encryption_state"
    echo -e "\e[1;92mWiFi Interface \e[1;94m= \e[1;93m$wifi_interface\n"
    
}

function dev_info () {
    
    devcode=$1
    modelname=$2
    
    properties=$(adb -s "$devcode" shell getprop)
    
    model=$(get_prop_details "ro.product.model")
    brand=$(get_prop_details "ro.product.vendor.brand")
    chipset=$(get_prop_details "ro.product.board")
    android=$(get_prop_details "ro.build.version.release")
    security_patch=$(get_prop_details "ro.build.version.security_patch")
    device=$(get_prop_details "ro.product.vendor.device")
    sim=$(get_prop_details "gsm.sim.operator.alpha")
    encryption_state=$(get_prop_details "ro.crypto.state")
    build_date=$(get_prop_details "ro.build.date")
    sdk_version=$(get_prop_details "ro.build.version.sdk")
    wifi_interface=$(get_prop_details "wifi.interface")
        
    print_info "$modelname"
    
    while true; do
        time=$(date +"%T")
        read -rp $'\e[93;1mDo you want to see all the Details\e[1;97m (Y/N) \e[93;1m? : \e[1;91m' yn
        case $yn in
            [Yy]* ) echo ;echo -e "\e[1;93m"; adb -s "$devcode" shell getprop > "sys-dump-info/$modelname-details-$time.log"  ; echo -e "THE DEVICE IS INITIALIZING WAIT" && sleep 1s; < "sys-dump-info/$modelname-details-$time.log" less; break ;;
            [Nn]* ) break;;
            * ) echo -e "\e[1;93mPlease answer it with\e[1;97m ( Y/N )\e[0m";;
        esac
    done
    
}

if [ "$total_dev" ==  "0" ]
then
    echo -e "\e[91;1mNO DEVICE CONNECTED"
else
    if [ "$total_dev" == "1" ]
    then
        
        devcode=$(echo "${dev[0]}" | awk '{print $1}')
        modelname=$(echo "${dev[0]}" | awk '{print $2}')
        
        echo -e "\e[93m1. \e[92m$devcode , \e[93mModel : \e[92m$modelname"
        dev_info "$devcode" "$modelname"
        
    else
        
        echo -e "\e[93mSelect the device to get the details :- \e[92m\n"
        
        for (( i=0; i<total_dev; i++ ));
        do
            devcode=$(echo "${dev[$i]}" | awk '{print $1}')
            modelname=$(echo "${dev[$i]}" | awk '{print $2}')
            echo -e "\e[93m1. \e[92m $devcode, \e[93mModel : \e[92m$modelname "
        done
        
        while true; do
            
            read -rp $'\n\e[1;4;91mEnter here\e[0m\e[24;1;97m : ' options
            [[ $options =~ ^[0-9]+$ ]] || { echo -e "\e[93m\nEnter a valid number"; continue; }
            if ((options  >= 1 && options <= total_dev));
            then
                
                devcode=$(echo "${dev[$options-1]}" | awk '{print $1}')
                modelname=$(echo "${dev[$options-1]}" | awk '{print $2}')
                
                dev_info "$devcode" "$modelname"
                
                break
                
            else
                echo -e "\e[93m\nEnter a valid number"
            fi
            
        done
        
    fi
fi

## Asking to Clear the screen
bash modules/HelperFunctions/AskClear