#!/usr/bin/env bash

echo -e "\e[1;93mExample :- \e[1;92m/home/user/Desktop/example.apk]"

#Total device count setting to zero initially
total_dev=0

## DEVICE ID & MODEL EXTARCT ##
dev=$(bash modules/HelperFunctions/GetDevices)

if [ "$dev" != "" ]; then
    total_dev=${#dev[@]}
fi

apk_install() {

    devcode=$1
    modelname=$2

    if [ "$to_install" == "0" ]; then
        if adb -s "$devcode" install -r "$apk_file_paths" &>/dev/null; then
            echo -e "\n\e[1;92mSuccessfully installed the 'apk' into device $modelname\n"
        else
            echo -e "\n\e[1;91mFailed installing the 'apk' into device $modelname\n"
        fi
    fi
}

apk_file_selector() {

    read -rp $'\e[1;91mEnter the path of the apk file\e[0m \e[24;1;97m : ' apk_file_paths
    if [ "$apk_file_paths" = "" ]; then
        echo -e "No path provided please provide the path to the apk file."
        apk_file_selector
    else
        if [ -f "$apk_file_paths" ]; then
            echo -e "\n\nUsing the provided file.\n\n"
            to_install=0
            apk_install "$to_install" "$apk_file_paths"
        else
            echo -e "The provided file does not exist please provide another pdf file or check the entered path\n"
            to_install=1
            apk_install "$to_install" "$apk_file_paths"
        fi
    fi

}

dev_install() {

    devcode=$1
    modelname=$2

    echo -e "\n\e[1;92mInstalling the 'apk' into device $devcode\n"
    apk_file_selector
    apk_install "$devcode" "$modelname"

}

if [ "$total_dev" == "0" ]; then
    echo -e "\e[91;1mNO DEVICE CONNECTED"
else
    if [ "$total_dev" == "1" ]; then

        devcode=$(echo "${dev[0]}" | awk '{print $1}')
        modelname=$(echo "${dev[0]}" | awk '{print $2}')

        echo -e "\e[93m1. \e[92m$devcode , \e[93mModel : \e[92m$modelname"
        dev_install "$devcode" "$modelname"

    else

        echo -e "\e[93mSelect the device to install 'apk' :- \e[92m\n"

        for ((i = 0; i < total_dev; i++)); do
            devcode=$(echo "${dev[$i]}" | awk '{print $1}')
            modelname=$(echo "${dev[$i]}" | awk '{print $2}')
            echo -e "\e[93m1. \e[92m $devcode, \e[93mModel : \e[92m$modelname "
        done

        while true; do

            read -rp $'\n\e[1;4;91mEnter here\e[0m\e[24;1;97m : ' options
            [[ $options =~ ^[0-9]+$ ]] || {
                echo -e "\e[93m\nEnter a valid number"
                continue
            }
            if ((options >= 1 && options <= total_dev)); then

                devcode=$(echo "${dev[$options - 1]}" | awk '{print $1}')
                modelname=$(echo "${dev[$options - 1]}" | awk '{print $2}')

                dev_install "$devcode" "$modelname"

                break

            else
                echo -e "\e[93m\nEnter a valid number"
            fi

        done

    fi
fi

## Asking to Clear the screen
bash modules/HelperFunctions/AskClear
