#!/usr/bin/env bash

#Total device count setting to zero initially
total_dev=0

## DEVICE ID & MODEL EXTARCT ##
dev=$(bash modules/HelperFunctions/GetDevices)

if [ "$dev" != "" ];
then
    total_dev=${#dev[@]}
fi

phone_no_take () {
    
    read -p $'\e[1;93mEnter the Phone number with country code in it : \e[0m' phone_no
    if [ "$phone_no" == "" ]
    then
        echo -e "\e[91mPlease enter the Phone number plz....\n"
        phone_no_take
    fi
    
}

sms_body_take () {
    
    read -p $'\e[1;93m\n\nWrite the SMS body here : \e[0m' sms_body
    if [ "$sms_body" == "" ]
    then
        echo -e "\e[91mPlease enter the SMS body plz....\n"
        sms_body_take
    fi
    
}

dev_sms_send () {
    
    devcode=$1
    phone_no_take
    sms_body_take
    adb -s $devcode shell am start -a android.intent.action.SENDTO -d sms:$phone_no --es sms_body "$sms_body" --ez exit_on_sent true >/dev/null 2>&1 | echo -e "\n\e[1;93mSENDING THE SMS\e[0m"
    adb -s $devcode shell input keyevent 22 >/dev/null 2>&1
    adb -s $devcode shell input keyevent 66 >/dev/null 2>&1
    
}


if [ "$total_dev" ==  "0" ]
then
    echo -e "\e[91;1mNO DEVICE CONNECTED"
else
    if [ "$total_dev" == "1" ]
    then
        
        devcode=$(echo ${dev[0]} | awk '{print $1}')
        modelname=$(echo ${dev[0]} | awk '{print $2}')
        
        echo -e "\e[93m1. \e[92m$devcode , \e[93mModel : \e[92m$modelname"
        dev_sms_send "$devcode"
        
    else
        
        echo -e "\e[93mSelect the device to send SMS :- \e[92m\n"
        for (( i=0; i<${total_dev}; i++ ));
        do
            devcode=$(echo ${dev[$i]} | awk '{print $1}')
            modelname=$(echo ${dev[$i]} | awk '{print $2}')
            echo -e "\e[93m1. \e[92m $devcode, \e[93mModel : \e[92m$modelname "
        done
        
        while [ 1 ]; do
            
            read -p $'\n\e[1;4;91mEnter here\e[0m\e[24;1;97m : ' options
            [[ $options =~ ^[0-9]+$ ]] || { echo -e "\e[93m\nEnter a valid number"; continue; }
            if ((options  >= 1 && options <= $total_dev));
            then
                
                devcode=$(echo ${dev[$options-1]} | awk '{print $1}')
                modelname=$(echo ${dev[$options-1]} | awk '{print $2}')
                
                dev_sms_send "$devcode"
                
                break
                
            else
                echo -e "\e[93m\nEnter a valid number"
            fi
            
        done
        
    fi
fi

## Asking to Clear the screen
bash modules/HelperFunctions/AskClear
