#!/usr/bin/env bash

#Total device count setting to zero initially
total_dev=0

## DEVICE ID & MODEL EXTARCT ##
dev=$(bash modules/HelperFunctions/GetDevices)

if [ "$dev" != "" ];
then
    total_dev=${#dev[@]}
fi

function if_file_exist_in_dev (){
    
    echo -e "\n\e[1;93mDon't include \e[1;92m/sdcard/\e[1;93m , Example :- \e[1;92mDownload/ashwini.pdf]\n"
    while [ 1 ]
    do
        read -p $'\e[1;93mEnter the path of file which you want to pull : \e[0m' file_to_copy_path
        if [ "$file_to_copy_path" == "" ]
        then
            echo -e "\e[91mPlease enter the path name plz....\n"
            if_file_exist_in_dev
        else
            tmp_chk=$(echo "if [ -f /sdcard/$file_to_copy_path ]; then echo '0'; else echo '1'; fi" | adb -s $devvv shell)
            if [ "$tmp_chk" == "0" ]
            then
                echo
                file_to_copy=0
                break
            else
                echo -e "\e[91mPlease enter the right path name plz....\n"
                if_file_exist_in_dev
            fi
        fi
        
    done
    
}

function if_dir_exist_in_dev (){
    
    echo -e "\n\e[1;93mDon't include \e[1;92m/sdcard/\e[1;93m , Example :- \e[1;92mDownload/]\n"
    while [ 1 ]
    do
        read -p $'\e[1;93mEnter the path of directory which you want to pull : \e[0m' dir_to_copy_path
        if [ "$dir_to_copy_path" == "" ]
        then
            echo -e "\e[91mPlease enter the path name plz....\n"
            if_dir_exist_in_dev
        else
            tmp_chk=$(echo "if [ -d /sdcard/$dir_to_copy_path ]; then echo '0'; else echo '1'; fi" | adb -s $devvv shell)
            if [ "$tmp_chk" == "0" ]
            then
                echo
                break
            else
                echo -e "\e[91mPlease enter the right path name plz....\n"
                if_dir_exist_in_dev
            fi
        fi
        
    done
    
}

function dev_custom_pull () {
    
    devicecode=$1
    modelname=$2
    
    echo -e "\e[93m1. \e[92mCopy File"
    echo -e "\e[93m2. \e[92mCopy Directory"
    while [ 1 ]
    do
        read -p $'\n\e[1;4;91mEnter here\e[0m\e[24;1;97m : ' options
        case $options in
            "1") if_file_exist_in_dev; break;;
            "2") if_dir_exist_in_dev; break;;
            *) echo -e "\n\e[1;4;91mENTER THE RIGHT OPTION BRO :- (1/2)\n";;
        esac
    done
    if [ -d $PWD/device-pull/"$modelname"-"$devcode"/ ]
    then
        echo -e "\e[92mDirectory exists. \n\e[93m"
    else
        tmp_dir=$(echo $PWD/device-pull/$modelname-$devcode)
        mkdir -p $tmp_dir
    fi
    
    if [ "$file_to_copy" == "0" ]
    then
        adb -s "$devcode" pull /sdcard/$file_to_copy_path $PWD/device-pull/$modelname-$devcode/
    else
        adb -s "$devcode" pull /sdcard/$dir_to_copy_path/ $PWD/device-pull/$modelname-$devcode/
    fi
    echo -e "\n\e[1;92mProcess complete.\n"
    
}

if [ "$total_dev" ==  "0" ]
then
    echo -e "\e[91;1mNO DEVICE CONNECTED"
else
    if [ "$total_dev" == "1" ]
    then
        
        devcode=$(echo ${dev[0]} | awk '{print $1}')
        modelname=$(echo ${dev[0]} | awk '{print $2}')
        
        echo -e "\e[93m1. \e[92m$devcode , \e[93mModel : \e[92m$modelname"
        dev_custom_pull "$devcode" "$modelname"
        
    else
        
        echo -e "\e[93mSelect the device to copy data :- \e[92m\n"
        for (( i=0; i<${total_dev}; i++ ));
        do
            devcode=$(echo ${dev[$i]} | awk '{print $1}')
            modelname=$(echo ${dev[$i]} | awk '{print $2}')
            echo -e "\e[93m1. \e[92m $devcode, \e[93mModel : \e[92m$modelname "
        done
        
        while [ 1 ]; do
            
            read -p $'\n\e[1;4;91mEnter here\e[0m\e[24;1;97m : ' options
            [[ $options =~ ^[0-9]+$ ]] || { echo -e "\e[93m\nEnter a valid number"; continue; }
            if ((options  >= 1 && options <= $total_dev));
            then
                
                devcode=$(echo ${dev[$options-1]} | awk '{print $1}')
                modelname=$(echo ${dev[$options-1]} | awk '{print $2}')
                dev_custom_pull "$devcode" "$modelname"
                
                break
                
            else
                echo -e "\e[93m\nEnter a valid number"
            fi
            
        done
        
    fi
fi

## Asking to Clear the screen
bash modules/HelperFunctions/AskClear