#!/usr/bin/env bash

read -rp $'\e[93;1m\nDo you want to clear the screen \e[1;97m (Y/n) \e[93;1m? : \e[1;91m' yn
case $yn in
    [Nn]* ) bash modules/function.sh;;
    * ) clear; bash modules/function.sh;;
esac