#!/usr/bin/env bash

#Total device count setting to zero initially
total_dev=0

dev=$(adb devices | sed -n '2,$p' | awk '{ print $1 }' 2> /dev/null)

if [ "$dev" != "" ];
then
    total_dev=${#dev[@]}
fi

if ((total_dev >= 1));
then
    for (( i=0; i<${total_dev}; i++ ));
    do
        devcode=$(echo ${dev[$i]} | awk '{print $1}')
        modelname=$(adb -s "$devcode" shell getprop ro.product.model | sed  's/ /_/g')
        dev[$i]=$(echo "$devcode $modelname")
    done
fi

echo -e $dev